#Deploy Apps
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonarr
    spec:
      volumes:
      - name: sonarr-storage
        persistentVolumeClaim:
          claimName: pvc-local
      containers:
      - image: lscr.io/linuxserver/sonarr
        name: sonarr
        volumeMounts:
          - name: sonarr-storage
            mountPath: "/config"
            subPath: "containers/sonarr"
          - name: sonarr-storage
            mountPath: "/shows"
            subPath: "media/shows"
          - name: sonarr-storage
            mountPath: "/torrentscompleted"
            subPath: "torrents/downloads"            
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-svc
spec:
  type: ClusterIP
  ports:
    - port: 8989
  selector:
    app: sonarr
---
#Deploy Apps
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: radarr
    spec:
      volumes:
      - name: radarr-storage
        persistentVolumeClaim:
          claimName: pvc-local
      containers:
      - image: lscr.io/linuxserver/radarr
        name: radarr
        volumeMounts:
          - name: radarr-storage
            mountPath: "/config"
            subPath: "containers/radarr"
          - name: radarr-storage
            mountPath: "/movies"
            subPath: "media/movies"
          - name: radarr-storage
            mountPath: "/torrentscompleted"
            subPath: "torrents/downloads"  
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-svc
spec:
  type: ClusterIP
  ports:
    - port: 7878
  selector:
    app: radarr
---
#Deploy Apps
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prowlarr
    spec:
      volumes:
      - name: prowlarr-storage
        persistentVolumeClaim:
          claimName: pvc-local
      containers:
      - image: lscr.io/linuxserver/prowlarr:develop
        name: prowlarr
        volumeMounts:
          - name: prowlarr-storage
            mountPath: "/config"
            subPath: "containers/prowlarr"
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-svc
spec:
  type: ClusterIP
  ports:
    - port: 9696
  selector:
    app: prowlarr